name: Build Windows Executable

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      shell: cmd

    - name: Verify requirements installation
      run: |
        pip list
      shell: cmd

    - name: Check Python environment
      run: |
        python --version
        python -c "import torch; print(torch.__version__)"
        python -c "import whisperx; print(whisperx.__version__)"
      shell: cmd

    - name: Build executable
      run: |
        pyinstaller --onefile -n TranscriptionApp whisperx/__main__.py --log-level DEBUG
      shell: cmd

    - name: Verify artifact exists
      run: |
        dir dist
      shell: cmd

    - name: Upload artifact
      if: success()
      uses: actions/upload-artifact@v3
      with:
        name: transcription-app
        path: dist/TranscriptionApp.exe